// File:        CMDNorth.h
// Date:        4.22.2004
// Author:      Chris Fangio
// Professor:   Dr. John Barton
// Description: Header file describing the CMDNorth object for program ACUMud
//              Moves a character north in the world

/* prevent multiple inclusions of header file */
#ifndef CMDNORTH_H
#define CMDNORTH_H

class CMDNorth : public Command {
   public:
      /* -----------DEFINE PUBLIC VARIABLES------------- */
      // NONE YET

      /* -----------DEFINE PUBLIC METHODS------------- */

   private:
      /* -----------DEFINE PRIVATE VARIABLES------------- */

      /* -----------DEFINE PRIVATE METHODS------------- */
      // NONE YET
};

#endif
